--
-- Script was generated by Devart dbForge Studio 2019 for PostgreSQL, Version 2.1.97.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 9/1/2019 2:00:48 PM
-- Server version: PostgreSQL 10.6 on x86_64-pc-mingw64, compiled by gcc.exe (Rev5, Built by MSYS2 project) 4.9.2, 64-bit
--


INSERT INTO fritease.public.ff_posts(id, date, image, ff5_users, statustext, complete, notified, url, created_at, updated_at) VALUES
(11, '2019-08-05', E'/images/banners/2019/09-06.png', E'[]', E'#FriTease 09/06\nTHEME 1: "FAKE"\nTHEME 2: "FLOW"\n\n#FF 5 peeps to follow 👁👁:\n[FF1]\n[FF2]\n[FF3]\n[FF4]\n[FF5]\n\nL/RT your favorites!\n@PromptList @PromptAdvant @thewritelist @writevent', false, null, null, null, null);
INSERT INTO fritease.public.ff_posts(id, date, image, ff5_users, statustext, complete, notified, url, created_at, updated_at) VALUES
(8, '2019-08-08', E'/images/banners/2019/08-09.png', E'[{"id":31247527,"screen_name":"S_Massey"},{"id":3413483375,"screen_name":"cheriesummers18"},{"id":373752071,"screen_name":"WillieHandler"},{"id":785546509995552800,"screen_name":"allitemplebooks"},{"id":2340870368,"screen_name":"BklynMercado"}]', E'#FriTease 08/09\nTHEME 1: "IGNORE"\nTHEME 2: "YEARN"\n\n#FF 5 peeps to follow 👁👁:\n@S_Massey\n@cheriesummers18\n@WillieHandler\n@allitemplebooks\n@BklynMercado\n\nL/RT your favorites!\n@PromptList @PromptAdvant @thewritelist @writevent', true, false, E'https://twitter.com/johnfpendleton/status/1160070168632078336', null, null);
INSERT INTO fritease.public.ff_posts(id, date, image, ff5_users, statustext, complete, notified, url, created_at, updated_at) VALUES
(10, '2019-08-15', E'/images/banners/2019/08-16.png', E'[{"id":755830003993079800,"screen_name":"IngmarAlbizu"},{"id":2278152015,"screen_name":"LetchfordLois"},{"id":896424226336505900,"screen_name":"anamuune"},{"id":26683817,"screen_name":"jenw0114"},{"id":863067124012601300,"screen_name":"Salen_Valari"}]', E'#FriTease 08/16\nTHEME 1: "COLLAPSE"\nTHEME 2: "CONTROL"\n\n#FF 5 peeps to follow 👁👁:\n@IngmarAlbizu\n@LetchfordLois\n@anamuune\n@jenw0114\n@Salen_Valari\n\nL/RT your favorites!\n@PromptList @PromptAdvant @thewritelist @writevent', true, null, E'https://twitter.com/johnfpendleton/status/1162137077175201800', null, null);