--
-- Script was generated by Devart dbForge Studio 2019 for PostgreSQL, Version 2.1.97.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 9/1/2019 2:00:48 PM
-- Server version: PostgreSQL 10.6 on x86_64-pc-mingw64, compiled by gcc.exe (Rev5, Built by MSYS2 project) 4.9.2, 64-bit
--


INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(1, E'/images/banners/2018/01-26.png', '2018-01-26', E'SKIN', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(2, E'/images/banners/2018/02-02.png', '2018-02-02', E'EMBRACE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(3, E'/images/banners/2018/02-09.png', '2018-02-09', E'SWEAT', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(4, E'/images/banners/2018/02-16.png', '2018-02-16', E'HANDS', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(5, E'/images/banners/2018/02-23.png', '2018-02-23', E'NEED', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(6, E'/images/banners/2018/03-02.png', '2018-03-02', E'GENTLE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(7, E'/images/banners/2018/03-09.png', '2018-03-09', E'URGE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(8, E'/images/banners/2018/03-16.png', '2018-03-16', E'HEAT', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(9, E'/images/banners/2018/03-23.png', '2018-03-23', E'STEEL', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(10, E'/images/banners/2018/03-30.png', '2018-03-30', E'CONTROL', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(11, E'/images/banners/2018/04-06.png', '2018-04-06', E'DARK', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(12, E'/images/banners/2018/04-13.png', '2018-04-13', E'FOOL', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(13, E'/images/banners/2018/04-20.png', '2018-04-20', E'TOUCH', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(14, E'/images/banners/2018/04-27.png', '2018-04-27', E'CURVE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(15, E'/images/banners/2018/05-04.png', '2018-05-04', E'AROUSE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(16, E'/images/banners/2018/05-11.png', '2018-05-11', E'LASH', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(17, E'/images/banners/2018/05-18.png', '2018-05-18', E'GLARE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(18, E'/images/banners/2018/05-25.png', '2018-05-25', E'CLOSE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(19, E'/images/banners/2018/06-01.png', '2018-06-01', E'HOPE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(20, E'/images/banners/2018/06-08.png', '2018-06-08', E'SINEW', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(21, E'/images/banners/2018/06-15.png', '2018-06-15', E'LIQUID', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(22, E'/images/banners/2018/06-22.png', '2018-06-22', E'MOON', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(23, E'/images/banners/2018/06-29.png', '2018-06-29', E'GIVE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(24, E'/images/banners/2018/07-06.png', '2018-07-06', E'PRESS', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(25, E'/images/banners/2018/07-13.png', '2018-07-13', E'FALL', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(26, E'/images/banners/2018/07-20.png', '2018-07-20', E'LIGHT', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(27, E'/images/banners/2018/07-27.png', '2018-07-27', E'DREAM', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(28, E'/images/banners/2018/08-03.png', '2018-08-03', E'BREAK', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(29, E'/images/banners/2018/08-10.png', '2018-08-10', E'FLAME', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(30, E'/images/banners/2018/08-17.png', '2018-08-17', E'QUIET', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(31, E'/images/banners/2018/08-24.png', '2018-08-24', E'DRIP', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(32, E'/images/banners/2018/08-31.png', '2018-08-31', E'DRIVE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(33, E'/images/banners/2018/09-07.png', '2018-09-07', E'BONE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(34, E'/images/banners/2018/09-14.png', '2018-09-14', E'SHOE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(35, E'/images/banners/2018/09-21.png', '2018-09-21', E'DRIFT', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(36, E'/images/banners/2018/09-28.png', '2018-09-28', E'SIN', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(37, E'/images/banners/2018/10-05.png', '2018-10-05', E'SWEET', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(38, E'/images/banners/2018/10-12.png', '2018-10-12', E'CLUTCH', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(39, E'/images/banners/2018/10-19.png', '2018-10-19', E'FINGERS', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(40, E'/images/banners/2018/10-26.png', '2018-10-26', E'CRY', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(41, E'/images/banners/2018/11-02.png', '2018-11-02', E'WINE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(42, E'/images/banners/2018/11-09.png', '2018-11-09', E'LUSH', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(43, E'/images/banners/2018/11-16.png', '2018-11-16', E'DRESS', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(44, E'/images/banners/2018/11-23.png', '2018-11-23', E'ARM', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(45, E'/images/banners/2018/11-30.png', '2018-11-30', E'VOICE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(46, E'/images/banners/2018/12-07.png', '2018-12-07', E'BREATH', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(47, E'/images/banners/2018/12-14.png', '2018-12-14', E'PAIN', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(48, E'/images/banners/2018/12-21.png', '2018-12-21', E'FACE', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(49, E'/images/banners/2018/12-28.png', '2018-12-28', E'END', E'', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(50, E'/images/banners/2019/01-04.png', '2019-01-04', E'STORM', E'QUEEN', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(51, E'/images/banners/2019/01-11.png', '2019-01-11', E'SHIFT', E'SLIDE', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(52, E'/images/banners/2019/01-18.png', '2019-01-18', E'BOND', E'BLEED', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(53, E'/images/banners/2019/01-25.png', '2019-01-25', E'MAGIC', E'MASTER', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(54, E'/images/banners/2019/02-01.png', '2019-02-01', E'WINE', E'WEEP', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(55, E'/images/banners/2019/02-08.png', '2019-02-08', E'LEER', E'LOST', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(56, E'/images/banners/2019/02-15.png', '2019-02-15', E'DRASTIC', E'DESIRE', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(57, E'/images/banners/2019/02-22.png', '2019-02-22', E'HEAVY', E'HONOR', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(58, E'/images/banners/2019/03-01.png', '2019-03-01', E'FURY', E'FRENZY', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(59, E'/images/banners/2019/03-08.png', '2019-03-08', E'ALOOF', E'ALARM', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(60, E'/images/banners/2019/03-22.png', '2019-03-22', E'RAGGED', E'SMOOTH', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(61, E'/images/banners/2019/03-29.png', '2019-03-29', E'DESPERATE', E'SEPARATE', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(62, E'/images/banners/2019/04-05.png', '2019-04-05', E'GLOWER', E'GLAMOUR', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(63, E'/images/banners/2019/04-12.png', '2019-04-12', E'STRIPE', E'STEAL', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(64, E'/images/banners/2019/04-19.png', '2019-04-19', E'INSIDE', E'INVOKE', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(65, E'/images/banners/2019/04-26.png', '2019-04-26', E'BETRAY', E'BREATHE', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(66, E'/images/banners/2019/05-03.png', '2019-05-03', E'FRUSTRATE', E'FLUSTER', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(67, E'/images/banners/2019/05-10.png', '2019-05-10', E'REVILE', E'REVEAL', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(68, E'/images/banners/2019/05-17.png', '2019-05-17', E'EVENING', E'MORNING', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(69, E'/images/banners/2019/05-24.png', '2019-05-24', E'HIDE', E'HELP', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(70, E'/images/banners/2019/05-31.png', '2019-05-31', E'SWIFT', E'SWEET', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(71, E'/images/banners/2019/06-07.png', '2019-06-07', E'SCREAM', E'WHISPER', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(72, E'/images/banners/2019/06-14.png', '2019-06-14', E'BURN', E'BLOW', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(73, E'/images/banners/2019/06-21.png', '2019-06-21', E'COPPER', E'GOLD', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(74, E'/images/banners/2019/06-28.png', '2019-06-28', E'SISTER', E'DAUGHTER', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(75, E'/images/banners/2019/07-05.png', '2019-07-05', E'LAVISH', E'LUSCIOUS', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(76, E'/images/banners/2019/07-12.png', '2019-07-12', E'BENEATH', E'BETWEEN', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(77, E'/images/banners/2019/07-19.png', '2019-07-19', E'BOLD', E'HUMBLE', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(78, E'/images/banners/2019/07-26.png', '2019-07-26', E'CLING', E'CARESS', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(79, E'/images/banners/2019/08-02.png', '2019-08-02', E'DISROBE', E'COVER', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(80, E'/images/banners/2019/08-09.png', '2019-08-09', E'IGNORE', E'YEARN', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(81, E'/images/banners/2019/08-16.png', '2019-08-16', E'COLLAPSE', E'CONTROL', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(82, E'/images/banners/2019/08-23.png', '2019-08-23', E'THRUST', E'THIRST', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(83, E'/images/banners/2019/08-30.png', '2019-08-30', E'RAIN', E'CLOUD', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(84, E'/images/banners/2019/09-13.png', '2019-09-13', E'THREAT', E'THREAD', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(86, E'/images/banners/2019/09-20.png', '2019-09-20', E'CONCRETE', E'LIQUID', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(87, E'/images/banners/2019/09-27.png', '2019-09-27', E'DRUM', E'DREAM', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(88, E'/images/banners/2019/10-04.png', '2019-10-04', E'CONSTRUCT', E'CONCEDE', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(89, E'/images/banners/2019/10-11.png', '2019-10-11', E'DESTROY', E'EMPOWER', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(90, E'/images/banners/2019/10-18.png', '2019-10-18', E'KNIFE', E'KNOT', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(91, E'/images/banners/2019/10-25.png', '2019-10-25', E'HORROR', E'PRINCE(SS)', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(92, E'/images/banners/2019/11-01.png', '2019-11-01', E'WICKED', E'WANDER', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(93, E'/images/banners/2019/11-08.png', '2019-11-08', E'CLEVER', E'CLASSIC', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(94, E'/images/banners/2019/11-15.png', '2019-11-15', E'SEAR', E'SOAR', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(95, E'/images/banners/2019/11-22.png', '2019-11-22', E'WRINKLE', E'GLEAN', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(96, E'/images/banners/2019/11-29.png', '2019-11-29', E'PLEAD', E'PLIANT', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(97, E'/images/banners/2019/12-06.png', '2019-12-06', E'SACRAMENT', E'INSTRUMENT', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(98, E'/images/banners/2019/12-13.png', '2019-12-13', E'CURSE', E'LUCK', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(99, E'/images/banners/2019/12-20.png', '2019-12-20', E'SCRATCH', E'SLIVER', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(100, E'/images/banners/2019/12-27.png', '2019-12-27', E'CONCLUSION', E'COMPULSION', null, null);
INSERT INTO fritease.public.ff_images(id, url, date, theme1, theme2, created_at, updated_at) VALUES
(85, E'/images/banners/2019/09-06.png', '2019-09-06', E'FAKE', E'FLOW', null, null);